/**
 * benchmarkChangelog.ts
 *
 * Structured revision log for ISC benchmark data and methodology changes.
 * Each entry documents what changed, why, which source drove it, and the
 * before/after values where applicable. Displayed on the /data-sources page.
 *
 * Add a new entry at the HEAD of BENCHMARK_CHANGELOG for every audit cycle.
 */

export type ChangeEntry = {
  /** Human-readable short name for the KPI or configuration item */
  item: string;
  itemAr: string;
  industry: string;
  industryAr: string;
  field: 'benchmark' | 'target' | 'weight';
  oldValue: string;
  newValue: string;
  /** ISO 8601 date (YYYY-MM-DD) */
  rationale: string;
  rationaleAr: string;
  source: string;
};

export type ChangelogRelease = {
  /** Semantic version for this data release */
  version: string;
  /** ISO 8601 date */
  date: string;
  titleEn: string;
  titleAr: string;
  summaryEn: string;
  summaryAr: string;
  changes: ChangeEntry[];
};

export const BENCHMARK_CHANGELOG: ChangelogRelease[] = [
  {
    version: '3.0',
    date: '2025-07-28',
    titleEn: '2024–2025 Market Data Refresh',
    titleAr: 'تحديث بيانات السوق 2024–2025',
    summaryEn:
      'Full audit of all GCC industry benchmarks and world-class targets against 2024 primary sources. ' +
      '26 industry-benchmark cells updated across 11 KPIs (fa, savings, pocycle, ttc, erpu, auto, stp, ppm, aud, mttr, lc), ' +
      '9 world-class targets tightened (savings, lc, auto, erpu, c2c, mttr), and scorecard dimension weights rebalanced ' +
      'to reflect the elevated strategic importance of ESG/Compliance per CIPS 2024.',
    summaryAr:
      'مراجعة شاملة لجميع مؤشرات أداء قطاعات دول الخليج وأفضل الممارسات العالمية وفق مصادر 2024 الأولية. ' +
      'تم تحديث 26 خلية في مؤشرات مرجعية صناعية عبر 11 مؤشر أداء رئيسي، وتشديد 9 أهداف عالمية المستوى، ' +
      'وإعادة توازن أوزان أبعاد بطاقة الأداء لتعكس الأهمية الاستراتيجية المتصاعدة للامتثال وفق تقرير CIPS 2024.',
    changes: [
      // ── Benchmarks ─────────────────────────────────────────────────────────
      {
        item: 'Forecast Accuracy — Retail/FMCG benchmark',
        itemAr: 'دقة التوقعات — قطاع التجزئة / السلع سريعة الدوران',
        industry: 'Retail / FMCG',
        industryAr: 'التجزئة / السلع الاستهلاكية',
        field: 'benchmark',
        oldValue: '68%',
        newValue: '72%',
        rationale: 'Gartner AI/ML demand-planning wave lifted median forecast accuracy across top GCC retailers.',
        rationaleAr: 'رفعت موجة الذكاء الاصطناعي من Gartner دقة التوقع المتوسطة لكبار تجار التجزئة في الخليج.',
        source: 'Gartner Supply Chain Top 25 (2024)',
      },
      {
        item: 'Forecast Accuracy — Logistics benchmark',
        itemAr: 'دقة التوقعات — قطاع اللوجستيات',
        industry: 'Logistics',
        industryAr: 'اللوجستيات',
        field: 'benchmark',
        oldValue: '70%',
        newValue: '74%',
        rationale: 'Logistics providers leading AI adoption reported improved forecast accuracy.',
        rationaleAr: 'حققت شركات اللوجستيات الرائدة في تبني الذكاء الاصطناعي دقة توقع محسّنة.',
        source: 'Gartner Supply Chain Top 25 (2024)',
      },
      {
        item: 'Procurement Savings — Retail/FMCG benchmark',
        itemAr: 'وفورات المشتريات — التجزئة / السلع الاستهلاكية',
        industry: 'Retail / FMCG',
        industryAr: 'التجزئة / السلع الاستهلاكية',
        field: 'benchmark',
        oldValue: '5.0%',
        newValue: '5.5%',
        rationale: 'CIPS 2024 survey reports improved category management and digital sourcing in FMCG.',
        rationaleAr: 'رصد مسح CIPS 2024 تحسناً في إدارة الفئات والمصادر الرقمية في قطاع السلع الاستهلاكية.',
        source: 'CIPS Benchmarking Report 2024',
      },
      {
        item: 'Procurement Savings — Oil & Gas benchmark',
        itemAr: 'وفورات المشتريات — النفط والغاز',
        industry: 'Oil & Gas',
        industryAr: 'النفط والغاز',
        field: 'benchmark',
        oldValue: '4.5%',
        newValue: '5.5%',
        rationale: 'Commodity AI-enabled sourcing and spot-market volatility management created new savings windows.',
        rationaleAr: 'أتاحت عمليات التوريد المدعومة بالذكاء الاصطناعي وإدارة تقلبات السلع نوافذ وفورات جديدة.',
        source: 'CIPS Benchmarking Report 2024 + Hackett Group 2024',
      },
      {
        item: 'PO Cycle Time — Government benchmark',
        itemAr: 'دورة أمر الشراء — القطاع الحكومي',
        industry: 'Government',
        industryAr: 'القطاع الحكومي',
        field: 'benchmark',
        oldValue: '42 days',
        newValue: '38 days',
        rationale: 'Saudi e-procurement and digital-government initiatives have accelerated public-sector PO cycle times.',
        rationaleAr: 'قلّصت مبادرات المشتريات الإلكترونية والحكومة الرقمية في السعودية دورة أوامر الشراء الحكومية.',
        source: 'CIPS Benchmarking Report 2024',
      },
      {
        item: 'Time-to-Contract — Retail/FMCG benchmark',
        itemAr: 'الوقت حتى التعاقد — التجزئة',
        industry: 'Retail / FMCG',
        industryAr: 'التجزئة / السلع الاستهلاكية',
        field: 'benchmark',
        oldValue: '45 days',
        newValue: '42 days',
        rationale: 'Digital contracting platforms shortened contract cycle times for retail procurement.',
        rationaleAr: 'قصّرت منصات العقود الرقمية دورة التعاقد في قطاع التجزئة.',
        source: 'IACCM / World Commerce & Contracting Annual Survey 2024',
      },
      {
        item: 'Time-to-Contract — Logistics benchmark',
        itemAr: 'الوقت حتى التعاقد — اللوجستيات',
        industry: 'Logistics',
        industryAr: 'اللوجستيات',
        field: 'benchmark',
        oldValue: '35 days',
        newValue: '30 days',
        rationale: 'Framework agreements and pre-qualified supplier lists shortened logistics contracting.',
        rationaleAr: 'اتفاقيات الإطار وقوائم الموردين المؤهلين مسبقاً قلّصت التعاقد اللوجستي.',
        source: 'IACCM / World Commerce & Contracting Annual Survey 2024',
      },
      {
        item: 'ERP Utilisation — Retail/FMCG benchmark',
        itemAr: 'استخدام نظام ERP — التجزئة',
        industry: 'Retail / FMCG',
        industryAr: 'التجزئة / السلع الاستهلاكية',
        field: 'benchmark',
        oldValue: '50%',
        newValue: '58%',
        rationale: 'GCC digital transformation accelerated ERP module activation in retail.',
        rationaleAr: 'عجّل التحول الرقمي في الخليج من تفعيل وحدات ERP في قطاع التجزئة.',
        source: 'McKinsey GCC Digital Transformation Survey 2024',
      },
      {
        item: 'ERP Utilisation — Manufacturing benchmark',
        itemAr: 'استخدام نظام ERP — التصنيع',
        industry: 'Manufacturing',
        industryAr: 'التصنيع',
        field: 'benchmark',
        oldValue: '42%',
        newValue: '50%',
        rationale: 'Industry 4.0 adoption in GCC manufacturing lifted ERP module utilisation.',
        rationaleAr: 'رفع تبني الصناعة 4.0 في التصنيع الخليجي مستوى استخدام وحدات ERP.',
        source: 'McKinsey GCC Digital Transformation Survey 2024',
      },
      {
        item: 'ERP Utilisation — Healthcare/Pharma benchmark',
        itemAr: 'استخدام نظام ERP — الرعاية الصحية',
        industry: 'Healthcare / Pharma',
        industryAr: 'الرعاية الصحية / الأدوية',
        field: 'benchmark',
        oldValue: '56%',
        newValue: '62%',
        rationale: 'Post-COVID compliance requirements accelerated hospital ERP deployments in MENA.',
        rationaleAr: 'متطلبات الامتثال ما بعد كوفيد عجّلت انتشار ERP في المستشفيات في منطقة الشرق الأوسط.',
        source: 'HIMSS EMEA 2023',
      },
      {
        item: 'ERP Utilisation — Government benchmark',
        itemAr: 'استخدام نظام ERP — القطاع الحكومي',
        industry: 'Government',
        industryAr: 'القطاع الحكومي',
        field: 'benchmark',
        oldValue: '35%',
        newValue: '42%',
        rationale: 'Saudi Riyadh Season and NEOM digital procurement mandates lifted government ERP usage.',
        rationaleAr: 'رفعت متطلبات الرقمنة في مشاريع الحكومة السعودية مستوى استخدام ERP.',
        source: 'Saudi Digital Government Authority Maturity Report 2024',
      },
      {
        item: 'Process Automation — Retail/FMCG benchmark',
        itemAr: 'أتمتة العمليات — التجزئة',
        industry: 'Retail / FMCG',
        industryAr: 'التجزئة / السلع الاستهلاكية',
        field: 'benchmark',
        oldValue: '28%',
        newValue: '35%',
        rationale: 'RPA and AI-driven P2P automation grew rapidly in GCC retail.',
        rationaleAr: 'نمت أتمتة P2P المدفوعة بالروبوتات والذكاء الاصطناعي بسرعة في التجزئة الخليجية.',
        source: 'Hackett Group World-Class Procurement 2024',
      },
      {
        item: 'Process Automation — Manufacturing benchmark',
        itemAr: 'أتمتة العمليات — التصنيع',
        industry: 'Manufacturing',
        industryAr: 'التصنيع',
        field: 'benchmark',
        oldValue: '22%',
        newValue: '30%',
        rationale: 'Industry 4.0 investment drove procurement automation gains in GCC manufacturing.',
        rationaleAr: 'دفعت استثمارات الصناعة 4.0 في التصنيع الخليجي إلى تحقيق مكاسب في أتمتة المشتريات.',
        source: 'Hackett Group World-Class Procurement 2024',
      },
      {
        item: 'Process Automation — Government benchmark',
        itemAr: 'أتمتة العمليات — القطاع الحكومي',
        industry: 'Government',
        industryAr: 'القطاع الحكومي',
        field: 'benchmark',
        oldValue: '14%',
        newValue: '20%',
        rationale: 'Saudi e-Government program and Etimad platform accelerated public-sector automation.',
        rationaleAr: 'برنامج الحكومة الإلكترونية السعودية ومنصة اعتماد عجّلا أتمتة القطاع الحكومي.',
        source: 'Saudi Digital Government Authority Maturity Report 2024',
      },
      {
        item: 'Process Automation — Logistics benchmark',
        itemAr: 'أتمتة العمليات — اللوجستيات',
        industry: 'Logistics',
        industryAr: 'اللوجستيات',
        field: 'benchmark',
        oldValue: '36%',
        newValue: '44%',
        rationale: 'Warehouse automation and AI routing lifted GCC logistics provider benchmarks.',
        rationaleAr: 'رفعت أتمتة المستودعات والتوجيه بالذكاء الاصطناعي مؤشرات مزودي اللوجستيات.',
        source: 'McKinsey Logistics Technology Survey 2024',
      },
      {
        item: 'Straight-Through PO Rate — Retail/FMCG benchmark',
        itemAr: 'معدل أوامر الشراء المباشرة — التجزئة',
        industry: 'Retail / FMCG',
        industryAr: 'التجزئة / السلع الاستهلاكية',
        field: 'benchmark',
        oldValue: '35%',
        newValue: '44%',
        rationale: 'AI-enabled P2P matching in retail drove touchless PO rates significantly higher.',
        rationaleAr: 'رفع التطابق الآلي بالذكاء الاصطناعي في P2P معدلات أوامر الشراء بلا لمس بشكل ملحوظ.',
        source: 'Hackett Group World-Class Procurement 2024',
      },
      {
        item: 'Straight-Through PO Rate — Manufacturing benchmark',
        itemAr: 'معدل أوامر الشراء المباشرة — التصنيع',
        industry: 'Manufacturing',
        industryAr: 'التصنيع',
        field: 'benchmark',
        oldValue: '25%',
        newValue: '33%',
        rationale: 'Catalogue-based ordering and ERP integration lifted touchless PO rates in manufacturing.',
        rationaleAr: 'رفع الطلب القائم على الكتالوج وتكامل ERP معدلات أوامر الشراء بلا لمس في التصنيع.',
        source: 'Hackett Group World-Class Procurement 2024',
      },
      {
        item: 'Straight-Through PO Rate — Logistics benchmark',
        itemAr: 'معدل أوامر الشراء المباشرة — اللوجستيات',
        industry: 'Logistics',
        industryAr: 'اللوجستيات',
        field: 'benchmark',
        oldValue: '40%',
        newValue: '50%',
        rationale: 'High-frequency spot purchasing and API-connected marketplaces drove STP rates up.',
        rationaleAr: 'أدى الشراء الفوري عالي التكرار والأسواق المتصلة بـ API إلى ارتفاع معدلات STP.',
        source: 'Hackett Group World-Class Procurement 2024',
      },
      {
        item: 'Defect Rate (PPM) — Healthcare/Pharma benchmark',
        itemAr: 'معدل العيوب (PPM) — الرعاية الصحية',
        industry: 'Healthcare / Pharma',
        industryAr: 'الرعاية الصحية / الأدوية',
        field: 'benchmark',
        oldValue: '500 PPM',
        newValue: '350 PPM',
        rationale: 'Tightened GMP enforcement and cold-chain standards post-2022 reduced defect rates.',
        rationaleAr: 'أدى تشديد تطبيق ممارسات التصنيع الجيد ومعايير سلسلة التبريد بعد 2022 إلى تقليص معدلات العيوب.',
        source: 'ISM Report on Business 2024',
      },
      {
        item: 'Audit Score — Oil & Gas benchmark',
        itemAr: 'درجة التدقيق — النفط والغاز',
        industry: 'Oil & Gas',
        industryAr: 'النفط والغاز',
        field: 'benchmark',
        oldValue: '68/100',
        newValue: '72/100',
        rationale: 'Tightening IOGP and IFC Performance Standards require higher audit readiness across O&G supply chains.',
        rationaleAr: 'تتطلب معايير IOGP وIFC المشددة استعداداً أعلى للتدقيق في سلاسل إمداد النفط والغاز.',
        source: 'IOGP Audit Standards Review 2023',
      },
      {
        item: 'MTTR — Retail/FMCG benchmark',
        itemAr: 'متوسط وقت الاسترداد — التجزئة',
        industry: 'Retail / FMCG',
        industryAr: 'التجزئة / السلع الاستهلاكية',
        field: 'benchmark',
        oldValue: '72h',
        newValue: '60h',
        rationale: 'AI-driven supplier risk early-warning systems shorten recovery windows in retail.',
        rationaleAr: 'تقصّر أنظمة الإنذار المبكر للمخاطر بالذكاء الاصطناعي نوافذ الاسترداد في التجزئة.',
        source: 'McKinsey Supply Chain Resilience 2024',
      },
      {
        item: 'MTTR — Logistics benchmark',
        itemAr: 'متوسط وقت الاسترداد — اللوجستيات',
        industry: 'Logistics',
        industryAr: 'اللوجستيات',
        field: 'benchmark',
        oldValue: '48h',
        newValue: '36h',
        rationale: 'Carrier redundancy and digital freight marketplaces reduced disruption recovery times.',
        rationaleAr: 'خفّض تكرار حاملي البضائع وأسواق الشحن الرقمية أوقات التعافي من الاضطرابات.',
        source: 'McKinsey Supply Chain Resilience 2024',
      },
      {
        item: 'Local Content — Oil & Gas benchmark',
        itemAr: 'المحتوى المحلي — النفط والغاز',
        industry: 'Oil & Gas',
        industryAr: 'النفط والغاز',
        field: 'benchmark',
        oldValue: '38%',
        newValue: '50%',
        rationale: 'Saudi Aramco IKTVA 2023 Progress Report shows the GCC O&G sector achieved 54% in 2023; GCC median set conservatively at 50%.',
        rationaleAr: 'أظهر تقرير IKTVA لأرامكو السعودية 2023 تحقيق قطاع النفط والغاز 54% — متوسط دول الخليج محافظ عند 50%.',
        source: 'Saudi Aramco IKTVA Progress Report 2023',
      },
      {
        item: 'Local Content — Government benchmark',
        itemAr: 'المحتوى المحلي — القطاع الحكومي',
        industry: 'Government',
        industryAr: 'القطاع الحكومي',
        field: 'benchmark',
        oldValue: '40%',
        newValue: '48%',
        rationale: 'GCC public-sector localisation mandates under Vision 2030 accelerated local content in government procurement.',
        rationaleAr: 'عجّلت تفويضات التوطين في القطاع الحكومي بدول الخليج ضمن رؤية 2030 من المحتوى المحلي في المشتريات الحكومية.',
        source: 'Saudi Aramco IKTVA Progress Report 2023 + Saudi NDMO',
      },
      {
        item: 'Local Content — Manufacturing benchmark',
        itemAr: 'المحتوى المحلي — التصنيع',
        industry: 'Manufacturing',
        industryAr: 'التصنيع',
        field: 'benchmark',
        oldValue: '30%',
        newValue: '36%',
        rationale: 'Saudi and UAE manufacturing localisation drives under Vision 2030 and Make It In The Emirates lifted sector median.',
        rationaleAr: 'رفعت مبادرات التصنيع المحلي في السعودية والإمارات ضمن رؤية 2030 و"اصنعها في الإمارات" متوسط القطاع.',
        source: 'Vision 2030 Localisation Progress Report 2023',
      },
      {
        item: 'Local Content — Construction benchmark',
        itemAr: 'المحتوى المحلي — البناء والإنشاء',
        industry: 'Construction',
        industryAr: 'البناء والإنشاء',
        field: 'benchmark',
        oldValue: '34%',
        newValue: '40%',
        rationale: 'NEOM and giga-project procurement mandates enforcing local content targets lifted sector benchmark.',
        rationaleAr: 'رفعت متطلبات المشتريات المحلية لمشاريع نيوم والمشاريع الكبرى مؤشر قطاع البناء.',
        source: 'Vision 2030 Giga-Projects Procurement Framework 2023',
      },

      // ── World-class targets ─────────────────────────────────────────────────
      {
        item: 'C2C Cycle Time — Food & Beverage target',
        itemAr: 'دورة النقدية للنقدية — الغذاء والمشروبات',
        industry: 'Food & Beverage',
        industryAr: 'الغذاء والمشروبات',
        field: 'target',
        oldValue: '≤10 days',
        newValue: '≤8 days',
        rationale: 'Gartner SCM Top 25 (2024) shows world-class food & beverage companies achieving ≤8 days C2C.',
        rationaleAr: 'تُظهر قائمة Gartner SCM Top 25 (2024) أن أفضل شركات الغذاء والمشروبات تحقق دورة نقدية ≤8 أيام.',
        source: 'Gartner Supply Chain Top 25 (2024)',
      },
      {
        item: 'Procurement Savings — Retail/FMCG target',
        itemAr: 'وفورات المشتريات — التجزئة (الهدف)',
        industry: 'Retail / FMCG',
        industryAr: 'التجزئة / السلع الاستهلاكية',
        field: 'target',
        oldValue: '8%',
        newValue: '9%',
        rationale: 'CIPS top-quartile procurement functions in FMCG now achieve 9%+ savings through AI sourcing.',
        rationaleAr: 'تحقق وظائف المشتريات في الربع الأعلى لقطاع السلع الاستهلاكية الآن وفورات 9% فأكثر عبر المصادر بالذكاء الاصطناعي.',
        source: 'CIPS Benchmarking Report 2024',
      },
      {
        item: 'Procurement Savings — Oil & Gas target',
        itemAr: 'وفورات المشتريات — النفط والغاز (الهدف)',
        industry: 'Oil & Gas',
        industryAr: 'النفط والغاز',
        field: 'target',
        oldValue: '8%',
        newValue: '10%',
        rationale: 'Hackett top-decile O&G procurement using AI spot-sourcing achieves 10% savings targets.',
        rationaleAr: 'تحقق مشتريات النفط والغاز في الشريحة العليا من Hackett باستخدام التوريد الفوري بالذكاء الاصطناعي أهداف وفورات بنسبة 10%.',
        source: 'Hackett Group World-Class Procurement 2024',
      },
      {
        item: 'ERP Utilisation — Healthcare/Pharma target',
        itemAr: 'استخدام ERP — الرعاية الصحية (الهدف)',
        industry: 'Healthcare / Pharma',
        industryAr: 'الرعاية الصحية / الأدوية',
        field: 'target',
        oldValue: '78%',
        newValue: '82%',
        rationale: 'HIMSS EMEA top-quartile health systems show 82%+ ERP module utilisation in 2024.',
        rationaleAr: 'تُظهر أنظمة الصحة في الربع الأعلى لمنطقة EMEA من HIMSS استخدام وحدات ERP بنسبة 82% فأكثر في 2024.',
        source: 'HIMSS EMEA Adoption Model Report 2024',
      },
      {
        item: 'Process Automation — Logistics target',
        itemAr: 'أتمتة العمليات — اللوجستيات (الهدف)',
        industry: 'Logistics',
        industryAr: 'اللوجستيات',
        field: 'target',
        oldValue: '60%',
        newValue: '70%',
        rationale: 'Hackett World-Class Procurement (2024) identifies 70% as the top-decile automation target for logistics.',
        rationaleAr: 'يحدد Hackett World-Class Procurement (2024) 70% كهدف أتمتة للشريحة العليا في قطاع اللوجستيات.',
        source: 'Hackett Group World-Class Procurement 2024',
      },
      {
        item: 'Local Content — Oil & Gas target',
        itemAr: 'المحتوى المحلي — النفط والغاز (الهدف)',
        industry: 'Oil & Gas',
        industryAr: 'النفط والغاز',
        field: 'target',
        oldValue: '55%',
        newValue: '65%',
        rationale: 'Aramco IKTVA 70% target; top 10% of GCC O&G achievers already at ≈65% in 2023.',
        rationaleAr: 'هدف IKTVA لأرامكو 70%؛ أفضل 10% من منجزي O&G في الخليج وصلوا بالفعل إلى ≈65% في 2023.',
        source: 'Saudi Aramco IKTVA Progress Report 2023',
      },
      {
        item: 'Local Content — Government target',
        itemAr: 'المحتوى المحلي — القطاع الحكومي (الهدف)',
        industry: 'Government',
        industryAr: 'القطاع الحكومي',
        field: 'target',
        oldValue: '60%',
        newValue: '68%',
        rationale: 'Saudi Vision 2030 IKTVA mandate trajectory points to 68% as the top-10% achievable target for government procurement by 2030.',
        rationaleAr: 'تشير مسيرة تفويض IKTVA برؤية 2030 السعودية إلى أن 68% هو الهدف الممكن تحقيقه للشريحة العليا في المشتريات الحكومية بحلول 2030.',
        source: 'Saudi NDMO + Vision 2030 Program Management Office 2024',
      },
      {
        item: 'MTTR — Retail/FMCG target',
        itemAr: 'متوسط وقت الاسترداد — التجزئة (الهدف)',
        industry: 'Retail / FMCG',
        industryAr: 'التجزئة / السلع الاستهلاكية',
        field: 'target',
        oldValue: '<36h',
        newValue: '<24h',
        rationale: 'McKinsey supply-chain resilience survey (2024) identifies <24h as the top-10% target for resilient retail supply chains.',
        rationaleAr: 'يُحدد مسح مرونة سلسلة التوريد من McKinsey (2024) أقل من 24 ساعة كهدف الشريحة العليا لسلاسل التوريد التجزئة المرنة.',
        source: 'McKinsey Supply Chain Resilience Survey 2024',
      },
      {
        item: 'MTTR — Logistics target',
        itemAr: 'متوسط وقت الاسترداد — اللوجستيات (الهدف)',
        industry: 'Logistics',
        industryAr: 'اللوجستيات',
        field: 'target',
        oldValue: '<24h',
        newValue: '<18h',
        rationale: 'Logistics leaders with multi-carrier redundancy and AI rerouting achieve <18h MTTR.',
        rationaleAr: 'يحقق قادة اللوجستيات الذين لديهم تكرار متعدد للناقلين وإعادة التوجيه بالذكاء الاصطناعي متوسط وقت استرداد أقل من 18 ساعة.',
        source: 'McKinsey Supply Chain Resilience Survey 2024',
      },

      // ── Scorecard weights ───────────────────────────────────────────────────
      {
        item: 'Supplier Scorecard — Cost Competitiveness weight',
        itemAr: 'بطاقة أداء الموردين — وزن التنافسية السعرية',
        industry: 'All industries',
        industryAr: 'جميع القطاعات',
        field: 'weight',
        oldValue: '20%',
        newValue: '18%',
        rationale: 'CIPS 2024 supplier evaluation framework elevates ESG/Compliance to near-equal weight with Cost.',
        rationaleAr: 'يرفع إطار تقييم الموردين من CIPS 2024 أوزان الامتثال/ESG لتضاهي تنافسية التكلفة.',
        source: 'CIPS Supplier Scorecard Benchmark 2024 + ISM Best Practice 2024',
      },
      {
        item: 'Supplier Scorecard — Compliance weight',
        itemAr: 'بطاقة أداء الموردين — وزن الامتثال',
        industry: 'All industries',
        industryAr: 'جميع القطاعات',
        field: 'weight',
        oldValue: '15%',
        newValue: '18%',
        rationale: 'ESG regulatory pressure (ISSB, EU CSRD, Saudi TCFD alignment) elevated compliance importance across GCC procurement functions.',
        rationaleAr: 'رفع الضغط التنظيمي لـ ESG أهمية الامتثال في وظائف المشتريات الخليجية.',
        source: 'CIPS Supplier Scorecard Benchmark 2024 + ISM Best Practice 2024',
      },
      {
        item: 'Supplier Scorecard — Innovation weight',
        itemAr: 'بطاقة أداء الموردين — وزن الابتكار',
        industry: 'All industries',
        industryAr: 'جميع القطاعات',
        field: 'weight',
        oldValue: '10%',
        newValue: '9%',
        rationale: 'Minor rebalance to bring total to exactly 100% following Cost and Compliance adjustments.',
        rationaleAr: 'إعادة توازن بسيطة ليصبح المجموع 100% بعد تعديلات التكلفة والامتثال.',
        source: 'ISC methodology alignment',
      },
    ],
  },

  {
    version: '2.0',
    date: '2025-03-15',
    titleEn: '7-Tier Industry-Percentile Scoring Model',
    titleAr: 'نموذج التقييم السبعي بنسب الصناعة',
    summaryEn:
      'Replaced the 6-tier GCC-centric scoring model with a 7-tier industry-percentile framework. ' +
      'New formula aligns scores to the global distribution around the benchmark median. ' +
      'All PO Cycle Time targets tightened by 30% to reflect AI-driven P2P best practice.',
    summaryAr:
      'تم استبدال نموذج التقييم السداسي المتمحور حول الخليج بإطار سباعي الدرجات يستند إلى نسب الصناعة العالمية. ' +
      'تعمل الصيغة الجديدة على توافق الدرجات مع التوزيع العالمي حول المتوسط المرجعي. ' +
      'شُدِّدت جميع أهداف دورة أوامر الشراء بنسبة 30% لتعكس أفضل ممارسات P2P المدعومة بالذكاء الاصطناعي.',
    changes: [],
  },

  {
    version: '1.0',
    date: '2024-09-01',
    titleEn: 'Initial Data Library Publication',
    titleAr: 'النشر الأولي لمكتبة البيانات',
    summaryEn:
      'First release of the ISC KPI benchmark library. Eight GCC industries, 24 KPI indicators, ' +
      'industry benchmarks and world-class targets sourced from 2022-2023 authoritative studies.',
    summaryAr:
      'الإصدار الأول لمكتبة مؤشرات الأداء الرئيسية من ISC. ثمانية قطاعات خليجية، 24 مؤشر أداء، ' +
      'مؤشرات مرجعية وأهداف عالمية المستوى مستقاة من دراسات موثوقة للفترة 2022-2023.',
    changes: [],
  },
];
