import { Router, type IRouter } from "express";
import healthRouter            from "./health";
import openaiRouter            from "./openai/index";
import notifyRouter            from "./notify";
import intelligenceRouter      from "./intelligence";
import assessmentRouter        from "./assessment";
import authRouter              from "./auth";
import submissionsRouter       from "./submissions";
import debugRouter             from "./debug";
import consultancyRouter       from "./consultancy";
import leadsRouter             from "./leads";
import feedbackRouter          from "./feedback";
import scorecardRosterRouter   from "./scorecardRoster";
import scorecardConfigRouter   from "./scorecardConfig";
import v1Router                from "./v1";
import integrationsRouter      from "./integrations";
import aiPlanRouter            from "./aiPlan";
import plansRouter             from "./plans";
import webhooksInboundRouter   from "./webhooksInbound";
import notificationsRouter     from "./notifications";
import adminAutomationsRouter  from "./adminAutomations";
import diagnosticRouter        from "./diagnostic";
import csrRouter               from "./csr";
import commandCentreRouter     from "./commandCentre";
import adminBenchmarksRouter   from "./adminBenchmarks";
import maturityRemediesRouter    from "./maturityRemedies";
import maturityGuestRouter       from "./maturityGuest";
import maturitySnapshotsRouter   from "./maturitySnapshots";
import reportGeneratorRouter   from "./reportGenerator";
import maturityEvidenceRouter  from "./maturityEvidence";
import adminEvidenceRouter     from "./adminEvidence";
import regulatoryContentRouter from "./regulatoryContent";
import claimRouter              from "./claim";
import entitlementsRouter       from "./entitlements";
import roiSummaryRouter         from "./roiSummary";
import tcoAnalysesRouter        from "./tcoAnalyses";
import tcoTrendSnapshotsRouter  from "./tcoTrendSnapshots";
import workingCapitalAnalysesRouter from "./workingCapitalAnalyses";
import spendVarianceAnalysesRouter from "./spendVarianceAnalyses";
import clmContractsRouter          from "./clmContracts";
import rarAnalysesRouter           from "./rarAnalyses";
import briefRouter                from "./brief";
import workbenchRouter             from "./workbench";
import clmGenerationRouter         from "./clmGeneration";
import clmReviewExtractionRouter   from "./clmReviewExtraction";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/openai",            openaiRouter);
router.use("/notify",            notifyRouter);
router.use("/auth",              authRouter);
router.use("/submissions",       submissionsRouter);
router.use("/consultancy",       consultancyRouter);
router.use("/leads",             leadsRouter);
router.use("/feedback",          feedbackRouter);
router.use("/debug",             debugRouter);
router.use("/scorecard-roster",  scorecardRosterRouter);
router.use("/scorecard-config",  scorecardConfigRouter);
router.use("/v1",                v1Router);
router.use("/integrations",      integrationsRouter);
router.use("/plans",             plansRouter);
router.use("/notifications",     notificationsRouter);
router.use("/admin/automations",  adminAutomationsRouter);
router.use("/admin/benchmarks",   adminBenchmarksRouter);
router.use("/report",            reportGeneratorRouter);
router.use(commandCentreRouter);
router.use(maturityRemediesRouter);
router.use(maturityGuestRouter);
router.use(maturitySnapshotsRouter);
router.use(aiPlanRouter);
router.use(intelligenceRouter);
router.use(assessmentRouter);
router.use(diagnosticRouter);
router.use(csrRouter);
router.use(maturityEvidenceRouter);
router.use(adminEvidenceRouter);
router.use("/regulatory",       regulatoryContentRouter);
router.use(claimRouter);
router.use(entitlementsRouter);
router.use(roiSummaryRouter);
router.use("/tco-analyses",     tcoAnalysesRouter);
router.use("/tco-trend-snapshots", tcoTrendSnapshotsRouter);
router.use("/working-capital-analyses", workingCapitalAnalysesRouter);
router.use("/spend-variance-analyses", spendVarianceAnalysesRouter);
router.use("/clm-contracts",           clmContractsRouter);
router.use("/rar-analyses",            rarAnalysesRouter);
router.use(briefRouter);
router.use(workbenchRouter);
router.use(clmGenerationRouter);
router.use(clmReviewExtractionRouter);
router.use(webhooksInboundRouter);

export default router;
