/**
 * SavedPlansSection — "Go to tool" link contains #ai-plan-tool hash (Task 472).
 *
 * Confirms that the href generated by toolRoute() for each known tool key is
 * appended with '#ai-plan-tool' so that arriving via the link scrolls directly
 * to the AI plan widget rather than the top of the page.
 */
import React from 'react';
import { render, cleanup, waitFor } from '@testing-library/react';
import { afterEach, describe, expect, it, vi } from 'vitest';

vi.mock('@/lib/apiBase', () => ({ API_BASE: 'http://test-server/api' }));

import { SavedPlansSection } from './SavedPlansSection';

afterEach(() => {
  vi.unstubAllGlobals();
  cleanup();
});

const KNOWN_TOOL_KEYS: Array<{ key: string; expectedPath: string }> = [
  { key: 'kraljic',              expectedPath: '/kraljic'                                    },
  { key: 'risk-register',       expectedPath: '/risk-management'                            },
  { key: 'procurement-catmgmt', expectedPath: '/solutions/procurement-excellence'           },
  { key: 'scorecard-1',         expectedPath: '/solutions/supplier-relationship-governance' },
];

describe('SavedPlansSection — "Go to tool" link href includes #ai-plan-tool (Task 472)', () => {
  for (const { key, expectedPath } of KNOWN_TOOL_KEYS) {
    it(`toolKey="${key}" → href "${expectedPath}#ai-plan-tool"`, async () => {
      vi.stubGlobal('fetch', vi.fn().mockResolvedValue({
        json: () => Promise.resolve({
          ok: true,
          plans: [{ toolKey: key, text: '## Plan\nContent.', savedAt: '2025-01-01T00:00:00Z' }],
        }),
      }));

      const { container } = render(<SavedPlansSection isAr={false} />);

      const link = await waitFor(() => {
        const el = container.querySelector('a[title="Go to tool"]') as HTMLAnchorElement | null;
        if (!el) throw new Error(`No "Go to tool" link for toolKey="${key}"`);
        return el;
      });

      expect(link.getAttribute('href')).toBe(`${expectedPath}#ai-plan-tool`);
    });
  }
});
