  /* ── 14U.2  ICV (In-Country Value) & Local Content ─────────────────────── */
  {
    id: 'uae-reg-icv',
    title: 'ICV (In-Country Value) & Local Content',
    titleAr: 'القيمة المضافة المحلية والمحتوى المحلي',
    hint: 'Source: Ministry of Industry & Advanced Technology (MOIAT) National ICV Programme, launched 2021 under "Projects of the 50". Score is based on audited financial statements across weighted pillars (local procurement, investment, Emiratisation) and directly affects tender competitiveness.',
    hintAr: 'المصدر: برنامج القيمة المضافة المحلية الوطني التابع لوزارة الصناعة والتقنية المتقدمة، أُطلق عام 2021 ضمن "مشاريع الخمسين". يُبنى التقييم على القوائم المالية المدققة عبر ركائز مرجّحة (الشراء المحلي، الاستثمار، التوطين) ويؤثر مباشرة على تنافسية المناقصات.',
    benchmarks: { gcc: 2.2, topQuartile: 4.0 },
    industryWeights: {
      manufacturing: 1.5, fmcg: 1.2, pharma: 1.3, retail: 1.0,
      logistics: 1.2, marine: 1.3, construction: 1.5, oil_gas: 1.5,
      government: 1.3, technology: 1.2, banking: 1.0, other: 1.0,
    },
    evidence: {
      label:   'ICV certificate (current cycle)',
      labelAr: 'شهادة القيمة المضافة المحلية (الدورة الحالية)',
      hint:    'Upload your current MOIAT-issued ICV certificate showing your score and certifying body.',
      hintAr:  'ارفع شهادة القيمة المضافة المحلية الحالية الصادرة عن الوزارة موضحًا الدرجة والجهة المُصدرة.',
    },
    frameworks: ['MOIAT', 'ICV Programme'],
    questions: [
      {
        q: 'How rigorously does your organisation prepare and maintain the stand-alone audited financial statements MOIAT requires for ICV certification, as distinct from consolidated group accounts?',
        qAr: 'ما مدى صرامة إعداد ومؤسستكم للقوائم المالية المدققة المستقلة التي تشترطها الوزارة لشهادة القيمة المضافة المحلية، تمييزًا عن الحسابات الموحّدة للمجموعة؟',
        levels: [
          'Stand-alone audited statements for the certified legal entity do not exist; only consolidated group accounts are available.',
          'Stand-alone statements are prepared only when an ICV renewal is imminent, causing delays.',
          'Stand-alone audited statements are prepared annually as a matter of course, aligned to the ICV certification cycle.',
          'Financial reporting is structured proactively to maximise ICV-relevant categories (local procurement, investment) within the audited statements.',
          'ICV-optimised financial structuring is a standing finance-function objective, with the audited statements consistently supporting a top-quartile ICV score.',
        ],
        levelsAr: [
          'القوائم المالية المدققة المستقلة للكيان القانوني المُعتَمَد غير موجودة؛ وتتوفر فقط الحسابات الموحّدة للمجموعة.',
          'تُعَّد القوائم المستقلة فقط عند اقتراب موعد تجديد الشهادة، مما يسبب تأخيرًا.',
          'تُعَّد القوائم المالية المدققة المستقلة سنويًا كإجراء معتاد، متماشية مع دورة الشهادة.',
          'التقارير المالية تُبنى استباقيًا لتعظيم الفئات ذات الصلة بالقيمة المضافة المحلية (الشراء المحلي، الاستثمار) ضمن القوائم المدققة.',
          'الهيكلة المالية المُحسَّنة للقيمة المضافة المحلية هدف ثابت لوظيفة المالية، والقوائم المدققة تدعم باستمرار درجة في الربع الأعلى.',
        ],
      },
      {
        q: 'How actively does your organisation manage local procurement spend to maximise its weighted contribution to the ICV score, relative to your sector\'s pillar weightings?',
        qAr: 'ما مدى فعالية إدارة مؤسستكم للإنفاق على الشراء المحلي لتعظيم مساهمته المرجّحة في درجة القيمة المضافة المحلية، مقارنة بأوزان ركائز قطاعكم؟',
        levels: [
          'Local procurement spend is not tracked separately from total procurement spend; ICV pillar weighting is unknown.',
          'Local vs. imported procurement spend is tracked, but not actively managed toward the ICV score.',
          'A defined process reviews the local-content share of procurement spend against ICV pillar weightings at least annually.',
          'Sourcing decisions actively favour ICV-eligible local suppliers where cost-competitive, with the impact on ICV score modelled before major awards.',
          'Local-content optimisation is embedded in category strategy; the organisation actively develops UAE-based suppliers to expand its ICV-eligible base.',
        ],
        levelsAr: [
          'الإنفاق على الشراء المحلي لا يُتابَع بمعزل عن إجمالي الإنفاق؛ ووزن ركائز القيمة المضافة المحلية مجهول.',
          'يُتابَع الإنفاق المحلي مقابل المستورد، لكن دون إدارته فعليًا نحو تحسين الدرجة.',
          'عملية محددة تراجع حصة المحتوى المحلي من الإنفاق مقابل أوزان الركائز سنويًا على الأقل.',
          'قرارات التوريد تُفضّل الموردين المحليين المؤهلين للقيمة المضافة عند التنافسية السعرية، مع نمذجة الأثر على الدرجة قبل الترسيات الكبرى.',
          'تحسين المحتوى المحلي مُدمَج في استراتيجية الفئات؛ والمؤسسة تطوّر فعليًا موردين إماراتيين لتوسيع قاعدتها المؤهلة.',
        ],
      },
      {
        q: 'How well does your organisation select and manage its relationship with MOIAT-authorised ICV certifying bodies to ensure accurate, defensible scoring?',
        qAr: 'ما مدى جودة اختيار مؤسستكم وإدارتها لعلاقتها مع الجهات المُعتَمَدة من الوزارة لإصدار شهادات القيمة المضافة المحلية لضمان تقييم دقيق وقابل للدفاع عنه؟',
        levels: [
          'No relationship exists with an ICV certifying body; certification, if held at all, is outdated or unmanaged.',
          'A certifying body is engaged only reactively when a tender requires proof of ICV score.',
          'An ICV certifying body is engaged on a defined annual cycle aligned to the certification renewal date.',
          'The certifying-body relationship is actively managed, with pre-audit reviews to catch scoring issues before formal submission.',
          'ICV certification is treated as a strategic capability: the organisation maintains a documented, audit-ready evidence trail year-round and consistently avoids score disputes.',
        ],
        levelsAr: [
          'لا توجد علاقة مع جهة معتمدة لإصدار الشهادة؛ والشهادة، إن وُجدت، قديمة أو غير مُدارة.',
          'تُستعان بجهة الشهادة فقط بشكل تفاعلي عندما تتطلب مناقصة إثبات الدرجة.',
          'جهة الشهادة تُستعان بها وفق دورة سنوية محددة متماشية مع تاريخ التجديد.',
          'العلاقة مع جهة الشهادة تُدار بفعالية، مع مراجعات ما قبل التدقيق لالتقاط مشكلات التقييم قبل التقديم الرسمي.',
          'شهادة القيمة المضافة المحلية تُعامَل كقدرة استراتيجية: تحتفظ المؤسسة بسجل أدلة موثّق وجاهز للتدقيق طوال العام وتتجنب باستمرار نزاعات الدرجة.',
        ],
      },
      {
        q: 'How effectively does your organisation use its ICV score as a competitive input to federal and Emirate-level tender bids, beyond simple compliance?',
        qAr: 'ما مدى فعالية استخدام مؤسستكم لدرجة القيمة المضافة المحلية كمُدخَل تنافسي في المناقصات الاتحادية وعلى مستوى الإمارات، بما يتجاوز مجرد الامتثال؟',
        levels: [
          'The ICV score is not referenced in bid preparation; its tender-scoring impact is unknown to the bid team.',
          'The ICV score is included in bid documentation when required, but not positioned as a competitive differentiator.',
          'Bid teams reference the ICV score and understand its weighting impact on tender evaluation for target opportunities.',
          'ICV score trajectory is actively managed ahead of major tender cycles, with improvement targets tied to specific bid opportunities.',
          'A top-tier ICV score is a marketed competitive advantage, actively cited in bids and client relationship management across federal and Emirate-level opportunities.',
        ],
        levelsAr: [
          'درجة القيمة المضافة المحلية لا تُذكَر عند إعداد المناقصات؛ وأثرها على تقييم المناقصة مجهول لفريق التقديم.',
          'تُدرَج الدرجة في وثائق المناقصة عند الطلب، لكن دون تقديمها كميزة تنافسية.',
          'فرق التقديم تُشير إلى الدرجة وتفهم أثر وزنها على تقييم المناقصات للفرص المستهدفة.',
          'مسار تحسين الدرجة يُدار فعليًا قبل دورات المناقصات الكبرى، مع أهداف تحسين مرتبطة بفرص مناقصات محددة.',
          'الدرجة المتقدمة ميزة تنافسية تُسوَّق فعليًا وتُذكَر في المناقصات وإدارة علاقات العملاء عبر الفرص الاتحادية وعلى مستوى الإمارات.',
        ],
      },
      {
        q: 'How well does your organisation coordinate ICV data (local procurement, investment, Emiratisation) across finance, procurement, and HR functions to avoid conflicting or stale submissions?',
        qAr: 'ما مدى جودة تنسيق مؤسستكم لبيانات القيمة المضافة المحلية (الشراء المحلي، الاستثمار، التوطين) بين وظائف المالية والمشتريات والموارد البشرية لتجنب التقديمات المتضاربة أو القديمة؟',
        levels: [
          'Finance, procurement, and HR maintain separate, unreconciled data; ICV submissions risk inconsistency across functions.',
          'Data is shared between functions only when the certifying body specifically requests it.',
          'A defined annual coordination process reconciles local-procurement, investment, and Emiratisation data before ICV submission.',
          'A shared data owner maintains real-time visibility across all ICV-relevant metrics ahead of each certification cycle.',
          'ICV data governance is fully integrated across finance, procurement, and HR systems, with automated reconciliation and zero submission discrepancies over the past two cycles.',
        ],
        levelsAr: [
          'المالية والمشتريات والموارد البشرية تحتفظ ببيانات منفصلة وغير مطابقة؛ وتقديمات القيمة المضافة المحلية معرّضة للتضارب بين الوظائف.',
          'تُشارَك البيانات بين الوظائف فقط عندما تطلبها جهة الشهادة تحديدًا.',
          'عملية تنسيق سنوية محددة تطابق بيانات الشراء المحلي والاستثمار والتوطين قبل التقديم.',
          'مالك بيانات مشترك يحتفظ برؤية آنية عبر جميع المؤشرات ذات الصلة قبل كل دورة شهادة.',
          'حوكمة بيانات القيمة المضافة المحلية مُدمَجة بالكامل عبر أنظمة المالية والمشتريات والموارد البشرية، مع مطابقة آلية ودون أي تباينات في التقديم خلال آخر دورتين.',
        ],
      },
    ],
  },

  /* ── 14U.3  Customs & Trade Compliance ──────────────────────── */
  {
    id: 'uae-reg-customs',
    title: 'Customs & Trade Compliance',
    titleAr: 'الامتثال الجمركي والتجاري',
    hint: 'Source: Federal Customs Authority (FCA) + Emirate-level customs (Dubai Customs, Abu Dhabi Customs, etc.), GCC Common Customs Tariff. Requires both a trade license and separate FCA customs registration. Free-zone goods are duty-free until transferred to the mainland (5% standard duty + VAT applies at that point).',
    hintAr: 'المصدر: الهيئة الاتحادية للجمارك + الجمارك على مستوى الإمارات (جمارك دبي، جمارك أبوظبي، إلخ)، والتعريفة الجمركية الموحدة الخليجية. يتطلب ترخيصًا تجاريًا وتسجيلًا جمركيًا منفصلًا لدى الهيئة الاتحادية. بضائع المناطق الحرة معفاة من الرسوم حتى تُنقَل إلى البر الرئيسي (تُطبّق الرسوم القياسية 5% + ضريبة القيمة المضافة عند ذلك).',
    benchmarks: { gcc: 2.4, topQuartile: 4.1 },
    industryWeights: {
      manufacturing: 1.5, fmcg: 1.4, pharma: 1.4, retail: 1.3,
      logistics: 1.5, marine: 1.5, construction: 1.2, oil_gas: 1.3,
      government: 1.0, technology: 1.0, banking: 0.5, other: 1.0,
    },
    evidence: {
      label:   'FCA customs registration + trade license',
      labelAr: 'التسجيل الجمركي الاتحادي والترخيص التجاري',
      hint:    'Upload your current Federal Customs Authority registration and trade license.',
      hintAr:  'ارفع تسجيلكم الحالي لدى الهيئة الاتحادية للجمارك والترخيص التجاري.',
    },
    frameworks: ['FCA', 'GCC Common Customs Tariff', 'Mirsal 2'],
    questions: [
      {
        q: 'How completely does your organisation maintain both the trade license and the separate Federal Customs Authority registration required to legally clear goods through UAE ports?',
        qAr: 'ما مدى اكتمال احتفاظ مؤسستكم بالترخيص التجاري والتسجيل الجمركي المنفصل لدى الهيئة الاتحادية للجمارك المطلوبين لتخليص البضائع قانونيًا عبر الموانئ الإماراتية؟',
        levels: [
          'Customs registration status is unknown; shipments have been held or delayed due to missing or lapsed registration.',
          'Both registrations exist but are tracked informally, with renewal dates not proactively monitored.',
          'A defined process tracks trade license and FCA registration renewal dates with advance reminders.',
          'Registration status is monitored across all operating entities and Emirates with automated renewal alerts.',
          'Trade license and customs registration compliance is fully governed with zero shipment delays attributable to registration lapses over the past 24 months.',
        ],
        levelsAr: [
          'حالة التسجيل الجمركي مجهولة؛ وتعرضّت شحنات للاحتجاز أو التأخير بسبب تسجيل مفقود أو منتهٍ.',
          'يوجد التسجيلان لكن يُتابَعان بشكل غير رسمي، ودون مراقبة استباقية لتواريخ التجديد.',
          'عملية محددة تتابع تواريخ تجديد الترخيص التجاري والتسجيل الجمركي مع تذكيرات مسبقة.',
          'حالة التسجيل تُراقَب عبر جميع الكيانات التشغيلية والإمارات مع تنبيهات تجديد آلية.',
          'الامتثال للترخيص التجاري والتسجيل الجمركي محوكَم بالكامل دون أي تأخير في الشحنات يُعزى لانتهاء التسجيل خلال آخر 24 شهرًا.',
        ],
      },
      {
        q: 'How accurately does your organisation classify goods under the GCC Common Customs Tariff (HS codes) and apply the correct duty treatment for mainland vs. free-zone movements?',
        qAr: 'ما مدى دقة تصنيف مؤسستكم للبضائع بموجب التعريفة الجمركية الموحدة الخليجية (رموز التنسيق) وتطبيق المعاملة الجمركية الصحيحة لحركة البضائع بين البر الرئيسي والمناطق الحرة؟',
        levels: [
          'HS code classification is done ad hoc, often by the freight forwarder, with no internal review or accountability.',
          'A basic HS code reference list exists but is not consistently applied or updated against tariff changes.',
          'HS classification is reviewed by a trained internal resource before shipment, with free-zone/mainland duty treatment explicitly checked.',
          'Classification accuracy is audited periodically, with corrective processes for any misclassification found.',
          'HS classification and duty-treatment determination are systematised with built-in tariff-change monitoring, achieving a sustained record of zero classification-driven customs disputes.',
        ],
        levelsAr: [
          'تصنيف رموز التنسيق يتم بشكل غير منتظم، غالبًا من وكيل الشحن، دون مراجعة أو مساءلة داخلية.',
          'توجد قائمة مرجعية أساسية للرموز لكنها لا تُطبّق باستمرار أو تُحدّث مقابل تغييرات التعريفة.',
          'يُراجع التصنيف من موظف داخلي مُدرّب قبل الشحن، مع فحص صريح لمعاملة الرسوم بين البر الرئيسي والمنطقة الحرة.',
          'دقة التصنيف تُدقّق دوريًا، مع عمليات تصحيحية لأي تصنيف خاطئ يُكتشَف.',
          'تحديد التصنيف ومعاملة الرسوم مُمنهَجان مع مراقبة مدمجة لتغييرات التعريفة، محققَين سجلاً مستدامًا من عدم وجود نزاعات جمركية بسبب التصنيف.',
        ],
      },
      {
        q: 'For organisations operating through a free zone, how well is the FZ Transit Out process (via Mirsal 2) managed when goods move to the mainland market?',
        qAr: 'بالنسبة للمؤسسات العاملة عبر منطقة حرة، ما مدى جودة إدارة عملية النقل الخارج من المنطقة الحرة (عبر مرسال 2) عند انتقال البضائع إلى السوق المحلي؟',
        levels: [
          'Free-zone-to-mainland transfers happen without formal Transit Out declarations, creating compliance exposure.',
          'Transit Out declarations are filed, but duty and VAT calculations are checked only occasionally for accuracy.',
          'A defined process files Transit Out declarations through Mirsal 2 with duty (5%) and VAT calculated and verified for every mainland transfer.',
          'Transit Out volume and cost are tracked and reconciled against finance records monthly.',
          'Free-zone-to-mainland transfer compliance is fully systematised with automated Mirsal 2 integration and a sustained record of zero duty/VAT discrepancies.',
        ],
        levelsAr: [
          'تنتقل البضائع من المنطقة الحرة إلى البر الرئيسي دون إقرارات نقل رسمية، مما يخلق تعرّضًا للمخاطر.',
          'تُقدّم إقرارات النقل، لكن حسابات الرسوم وضريبة القيمة المضافة تُفحَص أحيانًا فقط للدقة.',
          'عملية محددة تُقدّم إقرارات النقل عبر مرسال 2 مع حساب الرسوم (5%) والضريبة والتحقق منها لكل نقل إلى البر الرئيسي.',
          'حجم وتكلفة عمليات النقل تُتابَع وتُطابَق مع سجلات المالية شهريًا.',
          'الامتثال لنقل البضائع من المنطقة الحرة إلى البر الرئيسي مُمنهَج بالكامل مع تكامل آلي مع مرسال 2 وسجل مستدام من عدم وجود تباينات في الرسوم أو الضريبة.',
        ],
      },
      {
        q: 'How complete and audit-ready is your organisation\'s customs documentation (commercial invoices, certificates of origin, packing lists) across shipments?',
        qAr: 'ما مدى اكتمال وجاهزية التدقيق لمستندات الجمارك لدى مؤسستكم (الفواتير التجارية، شهادات المنشأ، قوائم التعبئة) عبر الشحنات؟',
        levels: [
          'Customs documentation is incomplete or inconsistent, causing frequent clearance delays.',
          'Documentation is generally complete but assembled reactively per shipment with no standard template.',
          'A standardised documentation package is used for every shipment, reviewed before submission.',
          'Documentation completeness is tracked as a KPI, with root-cause analysis for any clearance delay.',
          'Customs documentation is fully digitised and audit-ready at all times, supporting a sustained record of first-time clearance with no documentation-driven delays.',
        ],
        levelsAr: [
          'مستندات الجمارك غير مكتملة أو غير متسقة، مما يسبب تأخيرات متكررة في التخليص.',
          'المستندات مكتملة عمومًا لكن تُجمّع بشكل تفاعلي لكل شحنة دون نموذج موحد.',
          'حزمة مستندات موحدة تُستخدَم لكل شحنة، وتُراجَع قبل التقديم.',
          'اكتمال المستندات يُتابَع كمؤشر أداء، مع تحليل السبب الجذري لأي تأخير في التخليص.',
          'مستندات الجمارك رقمية بالكامل وجاهزة للتدقيق في كل وقت، وتدعم سجلاً مستدامًا من التخليص من أول مرة دون تأخيرات بسبب المستندات.',
        ],
      },
      {
        q: 'How proactively does your organisation monitor changes to UAE customs duty rules, tariff classifications, and free-zone regulations that could affect landed cost?',
        qAr: 'ما مدى استباقية مراقبة مؤسستكم للتغيرات في قواعد الرسوم الجمركية الإماراتية وتصنيفات التعريفة ولوائح المناطق الحرة التي قد تؤثر على التكلفة الإجمالية للوصول؟',
        levels: [
          'Regulatory changes are learned about only when a shipment is affected at the port.',
          'Some monitoring occurs informally through customs brokers or industry news, without a defined process.',
          'A designated function periodically reviews FCA and Emirate-level customs updates relevant to the organisation\'s trade lanes.',
          'Regulatory-change monitoring is proactive and systematic, with landed-cost impact assessed before changes take effect.',
          'Customs regulatory horizon-scanning is a governed function integrated into sourcing and pricing strategy, with external customs advisors engaged for material changes.',
        ],
        levelsAr: [
          'يُعرَف بالتغيرات النظامية فقط عندما تتأثر شحنة عند الميناء.',
          'تحدث بعض المراقبة بشكل غير رسمي عبر الوسطاء الجمركيين أو أخبار القطاع، دون عملية محددة.',
          'جهة محددة تراجع تحديثات الهيئة الاتحادية والجمارك على مستوى الإمارات ذات الصلة بمسارات تجارة المؤسسة دوريًا.',
          'مراقبة التغيرات النظامية استباقية ومنهجية، مع تقييم الأثر على التكلفة الإجمالية قبل سريان التغييرات.',
          'استشراف التغيرات الجمركية وظيفة محوكَمة ومُدمَجة في استراتيجية التوريد والتسعير، مع الاستعانة بمستشارين جمركيين خارجيين للتغيرات الجوهرية.',
        ],
      },
    ],
  },

