  /* ── 14U.6  Halal Certification & Compliance ───────────────── */
  {
    id: 'uae-reg-halal',
    title: 'Halal Certification & Compliance',
    titleAr: 'شهادة الحلال والامتثال',
    hint: 'Source: ESMA-accredited halal certification bodies, UAE.S 2055 standard. Mandatory for imported meat, poultry, and their derivatives; certificates specify scope and validity (1-3 years) with annual surveillance audits typically required.',
    hintAr: 'المصدر: جهات شهادة الحلال المعتمدة من الهيئة، معيار الإمارات UAE.S 2055. إلزامي للحوم والدواجن المستوردة ومشتقاتها؛ وتحدد الشهادات النطاق والصلاحية (1-3 سنوات) مع تدقيقات مراقبة سنوية مطلوبة عادةً.',
    benchmarks: { gcc: 2.5, topQuartile: 4.2 },
    industryWeights: {
      manufacturing: 0.5, fmcg: 1.5, pharma: 1.3, retail: 1.3,
      logistics: 0.5, marine: 0.5, construction: 0.5, oil_gas: 0.5,
      government: 0.5, technology: 0.5, banking: 0.5, other: 0.5,
    },
    evidence: {
      label:   'ESMA-accredited halal certificate',
      labelAr: 'شهادة الحلال المعتمدة من الهيئة',
      hint:    'Upload your current halal certificate(s) from an ESMA-accredited certifying body, showing scope and validity period.',
      hintAr:  'ارفع شهادة (شهادات) الحلال الحالية من جهة معتمدة من الهيئة، موضحة النطاق وفترة الصلاحية.',
    },
    frameworks: ['ESMA', 'UAE.S 2055'],
    questions: [
      {
        q: 'How completely does your organisation identify which products in its portfolio require mandatory halal certification for UAE market entry?',
        qAr: 'ما مدى اكتمال تحديد مؤسستكم للمنتجات في محفظتها التي تتطلب شهادة حلال إلزامية لدخول السوق الإماراتي؟',
        levels: [
          'Halal certification applicability is unknown at the product level; requirements are discovered only when a shipment is rejected at customs.',
          'Meat and poultry products are known to require certification, but derivative and adjacent products are not systematically reviewed.',
          'A defined process reviews every relevant product (meat, poultry, and derivatives) against halal certification requirements before market entry.',
          'Halal applicability review is embedded in the product-launch and supplier-onboarding process, with tracking across the full relevant portfolio.',
          'Halal certification classification is proactively managed with a governed register, achieving zero customs rejections due to missing certification.',
        ],
        levelsAr: [
          'انطباق شهادة الحلال على مستوى المنتج مجهول؛ وتُكتشَف المتطلبات فقط عند رفض شحنة في الجمارك.',
          'معروف أن اللحوم والدواجن تتطلب شهادة، لكن المنتجات المشتقة والمجاورة لا تُراجَع منهجيًا.',
          'عملية محددة تراجع كل منتج ذي صلة (لحوم، دواجن، ومشتقات) مقابل متطلبات شهادة الحلال قبل دخول السوق.',
          'مراجعة الانطباق مُدمَجة في عملية إطلاق المنتج وتأهيل الموردين، مع تتبّع عبر كامل المحفظة ذات الصلة.',
          'تصنيف شهادة الحلال يُدار استباقيًا بسجل محوكَم، محققًا صفر رفض جمركي بسبب نقص الشهادات.',
        ],
      },
      {
        q: 'How well does your organisation manage halal certificate validity periods (1–3 years) and renewal timing across its certified product portfolio?',
        qAr: 'ما مدى جودة إدارة مؤسستكم لفترات صلاحية شهادات الحلال (1-3 سنوات) وتوقيت التجديد عبر محفظة المنتجات المُعتَمَدة؟',
        levels: [
          'Certificate validity periods are not tracked; certificates have lapsed unnoticed, disrupting supply.',
          'Validity periods are known but tracked informally, without proactive renewal reminders.',
          'A defined register tracks validity and renewal dates for every halal certificate, with advance reminders set.',
          'Renewal is planned well ahead of expiry, coordinated with annual surveillance audit scheduling.',
          'Halal certificate lifecycle management is fully governed with automated tracking, achieving zero supply disruptions due to certificate lapse over the past 24 months.',
        ],
        levelsAr: [
          'فترات صلاحية الشهادات لا تُتابَع؛ وانتهت شهادات دون ملاحظة، مما عطّل الإمداد.',
          'فترات الصلاحية معروفة لكن تُتابَع بشكل غير رسمي، دون تذكيرات تجديد استباقية.',
          'سجل محدد يتابع تواريخ الصلاحية والتجديد لكل شهادة حلال، مع تحديد تذكيرات مسبقة.',
          'يُخطّط للتجديد قبل الانتهاء بوقت كافٍ، بالتنسيق مع جدولة تدقيقات المراقبة السنوية.',
          'إدارة دورة حياة شهادات الحلال محوكَمة بالكامل مع تتبّع آلي، محققةً صفر اضطرابات إمداد بسبب انتهاء الشهادة خلال آخر 24 شهرًا.',
        ],
      },
      {
        q: 'How rigorously does your organisation prepare for and pass the annual surveillance audits required to maintain halal certificate validity?',
        qAr: 'ما مدى صرامة استعداد مؤسستكم واجتيازها لتدقيقات المراقبة السنوية المطلوبة للحفاظ على صلاحية شهادة الحلال؟',
        levels: [
          'Surveillance audits are not prepared for in advance; audit findings have led to certificate suspension.',
          'Audits are addressed reactively when scheduled, with limited internal readiness review.',
          'A defined pre-audit checklist confirms facility and process readiness ahead of each scheduled surveillance audit.',
          'Facility readiness is maintained continuously (not just before audits) through periodic internal self-checks against halal standard criteria.',
          'Halal compliance readiness is a governed, continuously maintained state, with a sustained record of surveillance audits passed without corrective action.',
        ],
        levelsAr: [
          'تدقيقات المراقبة لا يُستعَدّ لها مسبقًا؛ وأدت نتائج التدقيق إلى تعليق الشهادة.',
          'تُعالَج التدقيقات بشكل تفاعلي عند جدولتها، بمراجعة جاهزية داخلية محدودة.',
          'قائمة تحقق محددة قبل التدقيق تؤكد جاهزية المنشأة والعملية قبل كل تدقيق مراقبة مجدول.',
          'جاهزية المنشأة تُحافَظ عليها باستمرار (لا قبل التدقيقات فقط) عبر فحوصات ذاتية دورية مقابل معايير معيار الحلال.',
          'جاهزية الامتثال للحلال حالة محوكَمة ومحافَظ عليها باستمرار، بسجل مستدام من اجتياز تدقيقات المراقبة دون إجراءات تصحيحية.',
        ],
      },
      {
        q: 'How well does your organisation verify halal integrity through the supply chain (sourcing, handling, storage segregation) beyond just holding a certificate?',
        qAr: 'ما مدى جودة تحقّق مؤسستكم من سلامة الحلال عبر سلسلة الإمداد (التوريد، المناولة، فصل التخزين) بما يتجاوز مجرد حيازة شهادة؟',
        levels: [
          'Halal integrity beyond certification is not actively managed; segregation of halal and non-halal goods is not verified.',
          'Basic awareness of segregation requirements exists, but verification is inconsistent across storage and handling.',
          'A defined process verifies halal segregation at sourcing, storage, and handling stages for certified products.',
          'Halal integrity is actively audited across the supply chain, including third-party logistics partners handling certified goods.',
          'End-to-end halal integrity assurance is a governed programme with full chain-of-custody traceability and a sustained record with no integrity breaches.',
        ],
        levelsAr: [
          'سلامة الحلال بما يتجاوز الشهادة لا تُدار فعليًا؛ ولا يُتحقّق من فصل البضائع الحلال وغير الحلال.',
          'يوجد وعي أساسي بمتطلبات الفصل، لكن التحقق غير متسق عبر التخزين والمناولة.',
          'عملية محددة تتحقق من فصل الحلال في مراحل التوريد والتخزين والمناولة للمنتجات المُعتَمَدة.',
          'سلامة الحلال تُدقّق فعليًا عبر سلسلة الإمداد، بما يشمل شركاء الخدمات اللوجستية من الغير المتعاملين مع البضائع المُعتَمَدة.',
          'ضمان سلامة الحلال من البداية للنهاية برنامج محوكَم بتتبّع كامل لسلسلة الحيازة وسجل مستدام دون أي خروقات للسلامة.',
        ],
      },
      {
        q: 'How proactively does your organisation select and manage relationships with ESMA-accredited halal certifying bodies to ensure reliable, defensible certification?',
        qAr: 'ما مدى استباقية اختيار مؤسستكم وإدارتها لعلاقاتها مع جهات شهادة الحلال المعتمدة من الهيئة لضمان شهادة موثوقة وقابلة للدفاع عنها؟',
        levels: [
          'No direct relationship exists with a halal certifying body; certification, where held, is managed entirely by a supplier or third party.',
          'A certifying body is engaged reactively, typically only when a certification lapse is discovered.',
          'A halal certifying body is engaged on a defined cycle aligned to certification and surveillance audit timing.',
          'The certifying-body relationship is actively managed, with pre-audit coordination to ensure smooth surveillance outcomes.',
          'Halal certification management is a governed strategic relationship, with documented evidence trails and a sustained record of dispute-free certification across all relevant products.',
        ],
        levelsAr: [
          'لا توجد علاقة مباشرة مع جهة شهادة حلال؛ وتُدار الشهادة، إن وُجدت، بالكامل من قبل مورّد أو طرف ثالث.',
          'تُستعان بجهة الشهادة بشكل تفاعلي، عادةً فقط عند اكتشاف انتهاء الشهادة.',
          'جهة شهادة الحلال تُستعان بها وفق دورة محددة متماشية مع توقيت الشهادة وتدقيق المراقبة.',
          'العلاقة مع جهة الشهادة تُدار فعليًا، مع تنسيق ما قبل التدقيق لضمان نتائج مراقبة سلسة.',
          'إدارة شهادة الحلال علاقة استراتيجية محوكَمة، بسجلات أدلة موثّقة وسجل مستدام من الشهادات دون نزاعات عبر جميع المنتجات ذات الصلة.',
        ],
      },
    ],
  },

  /* ── 14U.7  PDPL Data Privacy & Protection ───────────────── */
  {
    id: 'uae-reg-pdpl',
    title: 'PDPL Data Privacy & Protection',
    titleAr: 'قانون حماية البيانات الشخصية والخصوصية',
    hint: 'Source: Federal Decree-Law No. 45 of 2021 on the Protection of Personal Data, effective 2 January 2022, overseen by the UAE Data Office. Applies UAE-wide EXCLUDING financial free zones (DIFC, ADGM), which have their own separate data protection regimes — a distinction that matters for organisations operating across zones.',
    hintAr: 'المصدر: المرسوم بقانون اتحادي رقم 45 لسنة 2021 بشأن حماية البيانات الشخصية، ساري المفعول من 2 يناير 2022، وتشرف عليه دائرة البيانات الإماراتية. يُطبّق على مستوى الدولة باستثناء المناطق الحرة المالية (مركز دبي المالي العالمي، سوق أبوظبي العالمي)، التي لديها أنظمة حماية بيانات منفصلة خاصة بها — وهو تمييز مهم للمؤسسات العاملة عبر عدة مناطق.',
    benchmarks: { gcc: 2.3, topQuartile: 4.0 },
    industryWeights: {
      manufacturing: 1.0, fmcg: 1.0, pharma: 1.3, retail: 1.3,
      logistics: 1.0, marine: 0.5, construction: 0.5, oil_gas: 0.5,
      government: 1.5, technology: 1.5, banking: 1.5, other: 1.0,
    },
    evidence: {
      label:   'PDPL compliance policy / data inventory',
      labelAr: 'سياسة الامتثال لقانون حماية البيانات / جرد البيانات',
      hint:    'Upload your organisation\'s PDPL compliance policy or personal-data inventory covering supply chain-related data (supplier, employee, customer shipment records).',
      hintAr:  'ارفع سياسة الامتثال لقانون حماية البيانات أو جرد البيانات الشخصية لدى مؤسستكم المتعلق ببيانات سلسلة الإمداد (سجلات الموردين، الموظفين، شحنات العملاء).',
    },
    frameworks: ['Federal Decree-Law No. 45/2021', 'UAE Data Office'],
    questions: [
      {
        q: 'Does your organisation correctly determine whether Federal PDPL or a free-zone-specific regime (DIFC, ADGM) applies to each of its data-processing activities?',
        qAr: 'هل تُحدّد مؤسستكم بشكل صحيح ما إذا كان قانون حماية البيانات الاتحادي أو نظام خاص بمنطقة حرة (مركز دبي المالي، سوق أبوظبي العالمي) ينطبق على كل نشاط من أنشطة معالجة البيانات لديها؟',
        levels: [
          'The applicable data-protection regime (federal vs. free-zone) is not determined; the organisation is unaware which rules apply to which entity or activity.',
          'A general awareness exists that free zones may have different rules, but no formal determination has been made per entity.',
          'A documented assessment identifies which regime (Federal PDPL, DIFC, or ADGM) applies to each operating entity and data-processing activity.',
          'Regime applicability is reviewed whenever the organisation\'s structure or operations change (new entity, new free zone, new activity).',
          'Multi-regime data-protection applicability is a governed, continuously maintained determination, with legal sign-off for any cross-regime data flows.',
        ],
        levelsAr: [
          'النظام المُطبّق (الاتحادي مقابل المنطقة الحرة) غير محدد؛ والمؤسسة غير مدركة أي القواعد تنطبق على أي كيان أو نشاط.',
          'يوجد وعي عام بأن المناطق الحرة قد تملك قواعد مختلفة، لكن دون تحديد رسمي لكل كيان.',
          'تقييم موثّق يحدد أي نظام (الاتحادي، مركز دبي المالي، أو سوق أبوظبي العالمي) ينطبق على كل كيان تشغيلي ونشاط معالجة بيانات.',
          'انطباق النظام يُراجَع كلما تغيّر هيكل المؤسسة أو عملياتها (كيان جديد، منطقة حرة جديدة، نشاط جديد).',
          'انطباق نظام حماية البيانات متعدد الأنظمة تحديد محوكَم ومُحافَظ عليه باستمرار، مع اعتماد قانوني لأي تدفقات بيانات عابرة للأنظمة.',
        ],
      },
      {
        q: 'How complete is your organisation\'s inventory of personal data processed through supply chain operations (supplier records, employee data, customer shipment details)?',
        qAr: 'ما مدى اكتمال جرد مؤسستكم للبيانات الشخصية المُعالَجة عبر عمليات سلسلة الإمداد (سجلات الموردين، بيانات الموظفين، تفاصيل شحن العملاء)؟',
        levels: [
          'No data inventory exists; the organisation does not know what personal data it holds or where it resides.',
          'A partial, outdated inventory exists for some systems but is not comprehensive or regularly updated.',
          'A documented data inventory covers the main supply chain systems, updated at least annually.',
          'The data inventory is actively maintained and updated whenever a new system or data flow is introduced.',
          'Data inventory management is fully automated and continuously current, integrated into system change-management processes.',
        ],
        levelsAr: [
          'لا يوجد جرد للبيانات؛ والمؤسسة لا تعرف ما هي البيانات الشخصية التي تحتفظ بها أو أين تقيم.',
          'يوجد جرد جزئي وقديم لبعض الأنظمة لكنه غير شامل أو محدَّث بانتظام.',
          'جرد بيانات موثّق يغطي أنظمة سلسلة الإمداد الرئيسية، ويُحدّث سنويًا على الأقل.',
          'جرد البيانات يُحافَظ عليه ويُحدّث فعليًا كلما استُحدِث نظام أو تدفق بيانات جديد.',
          'إدارة جرد البيانات آلية بالكامل ومُحدّثة باستمرار، ومُدمَجة في عمليات إدارة التغيير للأنظمة.',
        ],
      },
      {
        q: 'How well does your organisation obtain and manage consent (or another lawful basis) for processing personal data collected through supply chain operations?',
        qAr: 'ما مدى جودة حصول مؤسستكم على الموافقة (أو أساس نظامي آخر) لمعالجة البيانات الشخصية المُجمّعة عبر عمليات سلسلة الإمداد وإدارتها؟',
        levels: [
          'Personal data is collected and processed without a defined lawful basis or consent mechanism.',
          'Consent or lawful-basis practices exist informally but are not documented or consistently applied.',
          'A documented policy defines the lawful basis (consent or otherwise) for each category of personal data processed, applied consistently.',
          'Consent/lawful-basis records are actively maintained and auditable, with a process to handle withdrawal of consent.',
          'Lawful-basis and consent management is a governed programme with automated record-keeping and a sustained record of zero unlawful-processing findings.',
        ],
        levelsAr: [
          'تُجمَع البيانات الشخصية وتُعالَج دون أساس نظامي محدد أو آلية موافقة.',
          'توجد ممارسات موافقة أو أساس نظامي بشكل غير رسمي لكن دون توثيق أو تطبيق متسق.',
          'سياسة موثّقة تحدد الأساس النظامي (موافقة أو غيرها) لكل فئة من البيانات الشخصية المُعالَجة، وتُطبّق باستمرار.',
          'سجلات الموافقة/الأساس النظامي تُحافَظ عليها فعليًا وقابلة للتدقيق، مع عملية للتعامل مع سحب الموافقة.',
          'إدارة الأساس النظامي والموافقة برنامج محوكَم بحفظ سجلات آلي وسجل مستدام من صفر نتائج معالجة غير قانونية.',
        ],
      },
      {
        q: 'How well does your organisation contractually bind third-party processors (logistics providers, customs brokers, IT vendors) to PDPL-compliant data-handling terms?',
        qAr: 'ما مدى جودة إلزام مؤسستكم تعاقديًا للمعالجين من الأطراف الثالثة (مزودو الخدمات اللوجستية، الوسطاء الجمركيون، موردو تقنية المعلومات) بشروط تعامل مع البيانات متوافقة مع قانون حماية البيانات؟',
        levels: [
          'Third-party contracts contain no data-protection clauses; processor compliance with PDPL is unknown.',
          'Some contracts reference data protection generically, but terms are not PDPL-specific or consistently applied.',
          'A standard PDPL-compliant data-processing clause is included in contracts with all relevant third-party processors.',
          'Third-party PDPL compliance is actively verified (e.g., through questionnaires or audits) before and during the contract term.',
          'Third-party data-processor governance is a mature, audited programme with a sustained record of zero PDPL-related third-party incidents.',
        ],
        levelsAr: [
          'عقود الأطراف الثالثة لا تحتوي على بنود حماية بيانات؛ وامتثال المعالج لقانون حماية البيانات مجهول.',
          'بعض العقود تشير إلى حماية البيانات بشكل عام، لكن الشروط ليست خاصة بالقانون أو مُطبّقة باستمرار.',
          'بند معالجة بيانات موحد متوافق مع القانون يُدرج في العقود مع جميع المعالجين من الأطراف الثالثة ذوي الصلة.',
          'امتثال الأطراف الثالثة للقانون يُتحقّق منه فعليًا (عبر استبيانات أو تدقيقات) قبل وأثناء مدة العقد.',
          'حوكمة معالجي البيانات من الأطراف الثالثة برنامج ناضج ومُدقّق بسجل مستدام من صفر حوادث متعلقة بالقانون لدى أطراف ثالثة.',
        ],
      },
      {
        q: 'How prepared is your organisation to detect, respond to, and report a personal data breach in line with PDPL and UAE Data Office expectations?',
        qAr: 'ما مدى استعداد مؤسستكم لاكتشاف اختراق بيانات شخصية والاستجابة له والإبلاغ عنه بما يتماشى مع القانون وتوقعات دائرة البيانات الإماراتية؟',
        levels: [
          'No breach-detection or response process exists; a breach would likely go undetected or unreported.',
          'General awareness of breach-reporting obligations exists, but no documented response plan or reporting timeline is defined.',
          'A documented data-breach response plan defines detection, escalation, and reporting steps aligned to PDPL requirements.',
          'The breach-response plan is tested periodically (tabletop exercises) and roles are clearly assigned across IT, legal, and operations.',
          'Breach detection and response is a mature, continuously monitored capability with automated alerting and a demonstrated ability to meet reporting timelines under real or simulated conditions.',
        ],
        levelsAr: [
          'لا توجد عملية لاكتشاف الاختراقات أو الاستجابة لها؛ ومن المرجّح ألا يُكتشَف أو يُبلّغ عن أي اختراق.',
          'يوجد وعي عام بالتزامات الإبلاغ عن الاختراقات، لكن دون خطة استجابة موثّقة أو إطار زمني محدد للإبلاغ.',
          'خطة استجابة موثّقة لاختراق البيانات تحدد خطوات الاكتشاف والتصعيد والإبلاغ بما يتماشى مع متطلبات القانون.',
          'خطة الاستجابة للاختراق تُختبَر دوريًا (تمارين محاكاة) والأدوار موزّعة بوضوح عبر تقنية المعلومات والقانون والعمليات.',
          'اكتشاف الاختراقات والاستجابة لها قدرة ناضجة ومراقَبة باستمرار بتنبيهات آلية وقدرة مُثبتة على الوفاء بالمهل الزمنية للإبلاغ في ظروف حقيقية أو محاكاة.',
        ],
      },
    ],
  },

];
