  /* ── 14U.4  Product Conformity & Standards (ESMA) ──────────────── */
  {
    id: 'uae-reg-conformity',
    title: 'Product Conformity & Standards (ESMA)',
    titleAr: 'مطابقة المنتجات والمعايير (هيئة الإمارات للمواصفات والمقاييس)',
    hint: 'Source: Emirates Authority for Standardisation and Metrology (ESMA) — the federal body for national standards, conformity assessment, and metrology.',
    hintAr: 'المصدر: هيئة الإمارات للمواصفات والمقاييس — الجهة الاتحادية للمعايير الوطنية وتقييم المطابقة والمقاييس.',
    benchmarks: { gcc: 2.3, topQuartile: 4.0 },
    industryWeights: {
      manufacturing: 1.5, fmcg: 1.5, pharma: 1.5, retail: 1.3,
      logistics: 0.5, marine: 0.5, construction: 1.3, oil_gas: 1.0,
      government: 0.5, technology: 1.0, banking: 0.5, other: 1.0,
    },
    evidence: {
      label:   'ESMA conformity/product registration certificates',
      labelAr: 'شهادات المطابقة/تسجيل المنتجات من الهيئة',
      hint:    'Upload current ESMA conformity assessment or product registration certificates for your product portfolio.',
      hintAr:  'ارفع شهادات تقييم المطابقة أو تسجيل المنتجات الحالية من الهيئة لمحفظة منتجاتكم.',
    },
    frameworks: ['ESMA', 'UAE.S Standards'],
    questions: [
      {
        q: 'How systematically does your organisation identify which of its products require ESMA conformity assessment or registration before entering the UAE market?',
        qAr: 'ما مدى منهجية تحديد مؤسستكم للمنتجات التي تتطلب تقييم مطابقة أو تسجيلًا من الهيئة قبل دخول السوق الإماراتي؟',
        levels: [
          'Product-level ESMA applicability is unknown; conformity requirements are discovered only when a shipment is rejected.',
          'Some products are known to require certification, but there is no systematic review of the full product portfolio.',
          'A defined process reviews every new product against ESMA conformity requirements before market entry.',
          'ESMA applicability review is embedded in the product-launch and supplier-onboarding process, with tracking across the full portfolio.',
          'Product conformity classification is proactively managed with a governed register, achieving zero market-entry rejections due to missing certification.',
        ],
        levelsAr: [
          'انطباق متطلبات الهيئة على المنتجات مجهول؛ وتُكتشَف متطلبات المطابقة فقط عند رفض شحنة.',
          'بعض المنتجات معروف أنها تتطلب شهادة، لكن دون مراجعة منهجية لكامل محفظة المنتجات.',
          'عملية محددة تراجع كل منتج جديد مقابل متطلبات مطابقة الهيئة قبل دخول السوق.',
          'مراجعة الانطباق مُدمَجة في عملية إطلاق المنتج وتأهيل الموردين، مع تتبّع عبر كامل المحفظة.',
          'تصنيف مطابقة المنتجات يُدار استباقيًا بسجل محوكَم، محققًا صفر رفض عند دخول السوق بسبب نقص الشهادات.',
        ],
      },
      {
        q: 'How well does your organisation manage the ESMA-accredited conformity certification process (application, inspection, certificate issuance) end-to-end?',
        qAr: 'ما مدى جودة إدارة مؤسستكم لعملية شهادة المطابقة المعتمدة من الهيئة (التقديم، التفتيش، إصدار الشهادة) من البداية للنهاية؟',
        levels: [
          'Certification is handled reactively, often by a supplier or agent, with no internal visibility into status or validity.',
          'Certificates exist but validity periods and renewal dates are not proactively tracked.',
          'A defined owner manages the certification process end-to-end, with renewal dates tracked and reminders set.',
          'The certification pipeline is actively managed across the full product portfolio, with pre-audit facility reviews to avoid inspection failures.',
          'ESMA certification management is a governed function with a sustained record of on-time renewals and zero certification-driven market disruptions.',
        ],
        levelsAr: [
          'تُدار الشهادات بشكل تفاعلي، غالبًا من مورد أو وكيل، دون رؤية داخلية لحالتها أو صلاحيتها.',
          'الشهادات موجودة لكن فترات الصلاحية وتواريخ التجديد لا تُتابَع استباقيًا.',
          'مالك محدد يدير عملية الشهادة من البداية للنهاية، مع متابعة تواريخ التجديد وتحديد تذكيرات.',
          'مسار الشهادات يُدار فعليًا عبر كامل محفظة المنتجات، مع مراجعات ما قبل التفتيش للمنشآت لتجنب فشل التفتيش.',
          'إدارة شهادات الهيئة وظيفة محوكَمة بسجل مستدام من التجديد في الوقت المحدد وصفر اضطرابات في السوق بسبب الشهادات.',
        ],
      },
      {
        q: 'How effectively does your organisation ensure supplier/manufacturer facilities meet ESMA inspection requirements ahead of certification or renewal?',
        qAr: 'ما مدى فعالية ضمان مؤسستكم لاستيفاء منشآت الموردين/المصنّعين لمتطلبات تفتيش الهيئة قبل الشهادة أو التجديد؟',
        levels: [
          'Supplier facility readiness for ESMA inspection is not assessed by the organisation; failures are discovered at inspection.',
          'Facility readiness is checked informally, often relying on the supplier\'s own assurance.',
          'A defined pre-inspection checklist is applied to key supplier facilities ahead of scheduled ESMA inspections.',
          'Facility readiness is actively managed with periodic self-audits against ESMA criteria between formal inspections.',
          'Supplier facility conformity readiness is a governed supplier-management KPI, with a sustained record of first-time inspection passes.',
        ],
        levelsAr: [
          'جاهزية منشآت الموردين لتفتيش الهيئة لا تُقيَّم من قبل المؤسسة؛ وتُكتشَف الإخفاقات عند التفتيش.',
          'تُفحَص جاهزية المنشآت بشكل غير رسمي، غالبًا بالاعتماد على تأكيد المورّد نفسه.',
          'قائمة تحقق محددة قبل التفتيش تُطبّق على منشآت الموردين الرئيسية قبل مواعيد التفتيش المجدولة من الهيئة.',
          'جاهزية المنشآت تُدار فعليًا مع تدقيق ذاتي دوري مقابل معايير الهيئة بين التفتيشات الرسمية.',
          'جاهزية مطابقة منشآت الموردين مؤشر أداء محوكَم لإدارة الموردين، بسجل مستدام من اجتياز التفتيش من أول مرة.',
        ],
      },
      {
        q: 'How well does your organisation track and respond to ESMA standard updates (UAE.S standards) that could change product compliance requirements?',
        qAr: 'ما مدى جودة تتبّع واستجابة مؤسستكم لتحديثات معايير الهيئة (معايير الإمارات) التي قد تُغيّر متطلبات مطابقة المنتجات؟',
        levels: [
          'Standard updates are learned about only when a product is rejected or flagged at customs.',
          'Some monitoring of ESMA updates occurs informally through industry contacts, without a defined process.',
          'A designated function periodically reviews ESMA standard updates relevant to the product portfolio.',
          'Standard-change monitoring is proactive and systematic, with product-impact assessments performed before changes take effect.',
          'ESMA regulatory horizon-scanning is a governed function integrated into product development, with material standard changes flagged to leadership before they take effect.',
        ],
        levelsAr: [
          'يُعرَف بتحديثات المعايير فقط عند رفض منتج أو الإشارة إليه في الجمارك.',
          'تحدث بعض مراقبة تحديثات الهيئة بشكل غير رسمي عبر جهات اتصال في القطاع، دون عملية محددة.',
          'جهة محددة تراجع تحديثات معايير الهيئة ذات الصلة بمحفظة المنتجات دوريًا.',
          'مراقبة تغيّر المعايير استباقية ومنهجية، مع تقييمات أثر على المنتجات تُجرى قبل سريان التغييرات.',
          'استشراف تغيرات معايير الهيئة وظيفة محوكَمة مُدمَجة في تطوير المنتجات، مع رفع التغييرات الجوهرية للقيادة قبل سريانها.',
        ],
      },
      {
        q: 'How complete is your organisation\'s documentation trail (test reports, certificates, technical files) supporting product conformity claims across your portfolio?',
        qAr: 'ما مدى اكتمال سجل مستندات مؤسستكم (تقارير الفحص، الشهادات، الملفات الفنية) الداعمة لمزاعم مطابقة المنتجات عبر المحفظة؟',
        levels: [
          'Conformity documentation is incomplete or scattered, with no central repository.',
          'Documentation exists for most products but is not consistently organised or readily retrievable.',
          'A central, organised documentation repository covers all products requiring ESMA conformity.',
          'Documentation completeness is tracked as a KPI, with gap-closure plans for any missing evidence.',
          'Conformity documentation is fully digitised, audit-ready, and integrated into a governed product-compliance system with zero documentation gaps.',
        ],
        levelsAr: [
          'مستندات المطابقة غير مكتملة أو متفرقة، دون مستودع مركزي.',
          'المستندات موجودة لمعظم المنتجات لكن غير منظمة باستمرار أو سهلة الاسترجاع.',
          'مستودع مستندات مركزي ومنظم يغطي جميع المنتجات التي تتطلب مطابقة الهيئة.',
          'اكتمال المستندات يُتابَع كمؤشر أداء، مع خطط لسد أي أدلة مفقودة.',
          'مستندات المطابقة رقمية بالكامل وجاهزة للتدقيق ومُدمَجة في نظام امتثال منتجات محوكَم دون أي فجوات مستندية.',
        ],
      },
    ],
  },

  /* ── 14U.5  Government Procurement (Federal / Abu Dhabi / Dubai) ─── */
  {
    id: 'uae-reg-procurement',
    title: 'Government Procurement (Federal / Abu Dhabi / Dubai)',
    titleAr: 'المشتريات الحكومية (الاتحادية / أبوظبي / دبي)',
    hint: 'Source: Federal Decree-Law No. 11 of 2023 on Federal Government Procurement; Abu Dhabi Government Procurement Gate (Department of Finance); Dubai Law No. 12 of 2020 on Contracts and Warehouse Management. Each jurisdiction has separate registration and evaluation rules — federal registration does not automatically qualify a bidder for Abu Dhabi or Dubai tenders.',
    hintAr: 'المصدر: المرسوم بقانون اتحادي رقم 11 لسنة 2023 بشأن المشتريات الحكومية الاتحادية؛ بوابة المشتريات الحكومية لأبوظبي (دائرة المالية)؛ قانون دبي رقم 12 لسنة 2020 بشأن العقود وإدارة المخازن. لكل جهة قواعد تسجيل وتقييم منفصلة — والتسجيل الاتحادي لا يؤهل تلقائيًا للمشاركة في مناقصات أبوظبي أو دبي.',
    benchmarks: { gcc: 2.1, topQuartile: 3.9 },
    industryWeights: {
      manufacturing: 1.0, fmcg: 0.5, pharma: 1.0, retail: 0.5,
      logistics: 1.0, marine: 1.0, construction: 1.5, oil_gas: 1.3,
      government: 1.5, technology: 1.2, banking: 0.5, other: 0.5,
    },
    evidence: {
      label:   'Government procurement portal registration(s)',
      labelAr: 'تسجيل بوابة (بوابات) المشتريات الحكومية',
      hint:    'Upload proof of active registration on the federal and/or relevant Emirate-level procurement portal(s) you bid through.',
      hintAr:  'ارفع إثبات التسجيل النشط في البوابة الاتحادية و/أو بوابات المشتريات على مستوى الإمارات ذات الصلة التي تقدّمون من خلالها.',
    },
    frameworks: ['Federal Decree-Law No. 11/2023', 'Abu Dhabi Procurement Gate', 'Dubai Law No. 12/2020'],
    questions: [
      {
        q: 'How clearly does your organisation understand and maintain registration across the specific government procurement jurisdictions it bids into (federal, Abu Dhabi, Dubai, or other Emirates)?',
        qAr: 'ما مدى وضوح فهم مؤسستكم واحتفاظها بالتسجيل عبر جهات المشتريات الحكومية المحددة التي تتقدّم إليها (الاتحادية، أبوظبي، دبي، أو إمارات أخرى)؟',
        levels: [
          'Registration status across jurisdictions is unclear; bids have been rejected due to missing or lapsed registration.',
          'Registration exists for at least one jurisdiction but is not systematically tracked across all jurisdictions bid into.',
          'A defined process tracks active registration status across every jurisdiction the organisation bids into.',
          'Registration is proactively maintained and expanded ahead of anticipated bidding activity in new jurisdictions.',
          'Multi-jurisdiction registration is a governed capability with zero bid disqualifications due to registration issues over the past 24 months.',
        ],
        levelsAr: [
          'حالة التسجيل عبر الجهات غير واضحة؛ ورُفضت مناقصات بسبب تسجيل مفقود أو منتهٍ.',
          'التسجيل موجود لجهة واحدة على الأقل لكن دون تتبّع منهجي عبر جميع الجهات المُتقدَّم إليها.',
          'عملية محددة تتابع حالة التسجيل النشط عبر كل جهة تتقدّم إليها المؤسسة.',
          'التسجيل يُحافَظ عليه ويُوسَّع استباقيًا قبل نشاط المناقصات المتوقع في جهات جديدة.',
          'التسجيل متعدد الجهات قدرة محوكَمة دون أي استبعاد من مناقصات بسبب مشكلات تسجيل خلال آخر 24 شهرًا.',
        ],
      },
      {
        q: 'How completely does your organisation maintain the prequalification evidence (completed-contract records, technical and financial capacity documentation, track record on similar projects) that UAE federal and Emirate-level tenders evaluate under criteria like financial solvency, technical capability, and project experience?',
        qAr: 'ما مدى اكتمال احتفاظ مؤسستكم بأدلة التأهيل المسبق (سجلات العقود المُنجزة، وثائق القدرة الفنية والمالية، السجل الحافل بمشاريع مماثلة) التي تُقيّم بموجبها المناقصات الاتحادية والمحلية في الإمارات وفق معايير مثل الملاءة المالية والقدرة الفنية والخبرة بالمشاريع؟',
        levels: [
          'Prequalification evidence (completed-contract records, technical/financial capacity documentation) is scattered or incomplete; prequalification or eligibility has been questioned or bids rejected as a result.',
          'Documentation exists but is assembled reactively per bid rather than maintained on an ongoing basis.',
          'A central, organised record of completed-contract evidence and technical/financial-capacity documentation supports prequalification for every relevant tender.',
          'This evidence is proactively updated as projects complete, ready for immediate use in any qualifying prequalification or bid.',
          'Prequalification-evidence management is a governed capability integrated with project closeout, with a sustained record of zero prequalification challenges.',
        ],
        levelsAr: [
          'أدلة التأهيل المسبق (سجلات العقود المُنجزة، وثائق القدرة الفنية والمالية) متفرقة أو غير مكتملة؛ وتم التشكيك في التأهيل أو رفض مناقصات نتيجة لذلك.',
          'المستندات موجودة لكن تُجمّع بشكل تفاعلي لكل مناقصة بدلًا من الحفاظ عليها باستمرار.',
          'سجل مركزي ومنظم لأدلة العقود المُنجزة ووثائق القدرة الفنية والمالية يدعم التأهيل المسبق لكل مناقصة ذات صلة.',
          'هذه الأدلة تُحدّث استباقيًا مع إنجاز المشاريع، وجاهزة للاستخدام الفوري في أي تأهيل مسبق أو مناقصة مؤهلة.',
          'إدارة أدلة التأهيل المسبق قدرة محوكَمة مُدمَجة مع إغلاق المشاريع، بسجل مستدام من عدم وجود تحديات في التأهيل المسبق.',
        ],
      },
      {
        q: 'How well does your organisation understand the distinctions between federal, Abu Dhabi, and Dubai procurement rules when structuring bids and contracts across jurisdictions?',
        qAr: 'ما مدى جودة فهم مؤسستكم للفروقات بين قواعد المشتريات الاتحادية وأبوظبي ودبي عند هيكلة المناقصات والعقود عبر الجهات؟',
        levels: [
          'Bids and contracts are prepared using a single generic template regardless of jurisdiction, risking non-compliance with jurisdiction-specific rules.',
          'Awareness of jurisdictional differences exists but is not consistently applied in bid/contract preparation.',
          'Jurisdiction-specific bid and contract templates are used, reflecting the relevant federal, Abu Dhabi, or Dubai procurement rules.',
          'Legal or procurement specialists review jurisdiction-specific compliance before every major submission.',
          'Multi-jurisdiction procurement expertise is a governed organisational capability, with a documented record of successfully navigating federal, Abu Dhabi, and Dubai requirements without dispute.',
        ],
        levelsAr: [
          'تُعَّد المناقصات والعقود بقالب عام موحد بغض النظر عن الجهة، مما يُخاطر بعدم الامتثال لقواعد خاصة بكل جهة.',
          'يوجد وعي بالفروقات بين الجهات لكن دون تطبيقه باستمرار عند إعداد المناقصات/العقود.',
          'تُستخدَم قوالب مناقصات وعقود خاصة بكل جهة، تعكس قواعد المشتريات الاتحادية أو أبوظبي أو دبي ذات الصلة.',
          'متخصصون قانونيون أو في المشتريات يراجعون الامتثال الخاص بكل جهة قبل كل تقديم رئيسي.',
          'الخبرة في المشتريات متعددة الجهات قدرة تنظيمية محوكَمة، بسجل موثّق من التعامل الناجح مع متطلبات الجهة الاتحادية وأبوظبي ودبي دون نزاع.',
        ],
      },
      {
        q: 'How proactively does your organisation monitor changes to federal and Emirate-level procurement law that could affect bidding eligibility or contract terms?',
        qAr: 'ما مدى استباقية مراقبة مؤسستكم لتغيرات قانون المشتريات الاتحادي وعلى مستوى الإمارات التي قد تؤثر على أهلية المناقصة أو شروط العقد؟',
        levels: [
          'Procurement law changes are learned about only when a bid is affected or rejected.',
          'Some monitoring occurs informally through industry contacts, without a defined process.',
          'A designated function periodically reviews federal and relevant Emirate-level procurement law updates.',
          'Regulatory-change monitoring is proactive and systematic, with bid-strategy impact assessed before changes take effect.',
          'Procurement regulatory horizon-scanning is a governed function integrated into business development strategy, with legal advisors engaged for material changes across all jurisdictions bid into.',
        ],
        levelsAr: [
          'يُعرَف بتغيرات قانون المشتريات فقط عندما تتأثر مناقصة أو تُرفَض.',
          'تحدث بعض المراقبة بشكل غير رسمي عبر جهات اتصال في القطاع، دون عملية محددة.',
          'جهة محددة تراجع تحديثات قانون المشتريات الاتحادي وعلى مستوى الإمارة ذات الصلة دوريًا.',
          'مراقبة التغيرات النظامية استباقية ومنهجية، مع تقييم أثرها على استراتيجية المناقصات قبل سريانها.',
          'استشراف تغيرات قانون المشتريات وظيفة محوكَمة مُدمَجة في استراتيجية تطوير الأعمال، مع الاستعانة بمستشارين قانونيين للتغيرات الجوهرية عبر كل الجهات المُتقدَّم إليها.',
        ],
      },
    ],
  },

